import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import {Box, Flex, Theme} from "@radix-ui/themes";
import {ThemeProvider} from "next-themes";
import Navbar from "@/app/components/Navbar";
import React from "react";
export const metadata: Metadata = {
  title: "Burn Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{margin: 0, height: "100%"}}>
        <ThemeProvider attribute="class">
          <Theme accentColor="purple" grayColor="auto" panelBackground="solid" scaling="105%">
            <Flex direction="column" minHeight="100vh" height="100%">
              <Box position="sticky">
                <Navbar justify={"end"} links={[
                  { href: '/', label: 'Home' },
                  { href: '/shows', label: 'Shows & Podcasts' },
                  { href: '/scheduling', label: 'Scheduling' },
                  { href: '/posts', label: 'Posts' },
                ]}/>
              </Box>

              {children}
            </Flex>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
