import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import {Box, Flex, Theme} from "@radix-ui/themes";
import {ThemeProvider} from "next-themes";
import Navbar from "@/app/components/Navbar";
import React from "react";
import {AuthProvider} from "@/auth/AuthContext";
import {ToastProvider} from "@/app/components/Toast";
import RootNavbar from "@/app/components/RootNavbar";
export const metadata: Metadata = {
  title: "Burn Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{margin: 0, height: "100%"}}>
      <AuthProvider>
        <ThemeProvider attribute="class">
          <Theme accentColor="purple" grayColor="auto" panelBackground="solid" scaling="105%">
            <Flex direction="column" minHeight="100vh" height="100%">
              <Box position="sticky">
                <RootNavbar />
              </Box>

              <ToastProvider>
                {children}
              </ToastProvider>
            </Flex>
          </Theme>
        </ThemeProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
