import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import {Container, Flex, Theme} from "@radix-ui/themes";
import {ThemeProvider} from "next-themes";
import Navbar from "@/app/components/Navbar";

export const metadata: Metadata = {
  title: "Burn Admin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body style={{margin: 0}}>
        <ThemeProvider attribute="class">
          <Theme accentColor="purple" grayColor="mauve" panelBackground="solid" scaling="105%">
              <Container size="8">
                <Flex direction="column" minHeight="100vh">
                  <Navbar justify={"end"} links={[
                    { href: '/', label: 'Home' },
                    { href: '/shows', label: 'Shows & Podcasts' },
                    { href: '/scheduling', label: 'Scheduling' },
                    { href: '/posts', label: 'Posts' },
                  ]}/>
                  {children}
                </Flex>
              </Container>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
